const foodPictureImagesNew = [
  {'name': 'Beef Rendang','url':'images/dishes/beef-rendang.jpg'},
  {'name': 'Blackened Beef','url':'images/dishes/beef-with-green-tomato.jpg'},
  {'name': 'Black Pudding','url':'images/dishes/black-pudding.jpg'},
  {'name': 'Bruscetta','url':'images/dishes/bruscetta.jpg'},
  {'name': 'Cheese Noodles','url':'images/dishes/cheese-noodles.jpg'},
  {'name': 'Chilli Ribs','url':'images/dishes/chilli-ribs.jpg'},
  {'name': 'Clam Veloute','url':'images/dishes/clam-veloute.jpg'},
  {'name': 'Cumberland Sauce','url':'images/dishes/cumberland-sauce.jpg'},
  {'name': 'Dauphinoise Potatos','url':'images/dishes/dauphinoise.jpg'},
  {'name': 'Dosas','url':'images/dishes/dosa.jpg'},
  {'name': 'Dragon Rolls','url':'images/dishes/dragon-rolls.jpg'},
  {'name': 'Eggs Benedict','url':'images/dishes/eggs-benedict.jpg'},
  {'name': 'Garlic Prawns','url':'images/dishes/garlic-prawns.jpg'},
  {'name': 'Gochujang Eggs','url':'images/dishes/gochujang-eggs.jpg'},
  {'name': 'Guacamole','url':'images/dishes/guacamole.jpg'},
  {'name': 'Jerk Pork','url':'images/dishes/jerk-pork.jpg'},
  {'name': 'Beef Jerky','url':'images/dishes/jerky.jpg'},
  {'name': 'Korean Pork','url':'images/dishes/korean-pork.jpg'},
  {'name': 'Lamb Kebabs','url':'images/dishes/lamb-kebabs.jpg'},
  {'name': 'Lamb Ramen','url':'images/dishes/lamb-ramen.jpg'},
  {'name': 'Lemon Risotto','url':'images/dishes/lemon-risotto.jpg'},
  {'name': 'Jjajangmen','url':'images/dishes/looking-at-noodles.jpg'},
  {'name': 'Meatballs','url':'images/dishes/meatballs.jpg'},
  {'name': 'Mushroom Omelette','url':'images/dishes/mushroom-omelette.jpg'},
  {'name': 'Mushroom Pizza','url':'images/dishes/mushroom-pizza.jpg'},
  {'name': 'Lime Pickle','url':'images/dishes/nimbu-achar.jpg'},
  {'name': 'Oyster Fritters','url':'images/dishes/oyster-fritters.jpg'},
  {'name': 'Oysters Rockefella','url':'images/dishes/oysters-rockefella.jpg'},
  {'name': 'Padron Peppers','url':'images/dishes/padron-peppers.jpg'},
  {'name': 'Papaya Salad','url':'images/dishes/papaya-salad.jpg'},
  {'name': 'Pea and Mint Soup','url':'images/dishes/pea-and-mint-soup.jpg'},
  {'name': 'Pho','url':'images/dishes/pho.jpg'},
  {'name': 'Poke Bowl','url':'images/dishes/poke-bowl.jpg'},
  {'name': 'Pork Belly Ramen','url':'images/dishes/pork-belly-ramen.jpg'},
  {'name': 'Pork Chops','url':'images/dishes/pork-chops.jpg'},
  {'name': 'Ramen Eggs','url':'images/dishes/ramen-eggs.jpg'},
  {'name': 'Rice and Egg','url':'images/dishes/rice-and-egg.jpg'},
  {'name': 'Homemade Salami','url':'images/dishes/salami.jpg'},
  {'name': 'Fiery Scotch Eggs','url':'images/dishes/scotch-eggs.jpg'},
  {'name': 'Shoryu Ramen','url':'images/dishes/shoryu-ramen.jpg'  },
  {'name': 'Shrimp Tacos','url':'images/dishes/shrimp-tacos.jpg'},
  {'name': 'Homemade Ramen Noodles','url':'images/dishes/smiley-noodles.jpg'},
  {'name': 'Home-smoked Mackerel','url':'images/dishes/smoked-mackerel.jpg'},
  {'name': 'Spaghetti and Pesto','url':'images/dishes/spaghetti.jpg'},
  {'name': 'Proper Steak','url':'images/dishes/steak.jpg'},
  {'name': 'Tonkotsu Ramen','url':'images/dishes/tonkotsu-ramen.jpg'},
  {'name': 'Turkish Salad','url':'images/dishes/turkish-salad.jpg'},
  {'name': 'Vegan Con Carne','url':'images/dishes/vegan-con-carne.jpg'},
];

module.exports = foodPictureImagesNew;